### ISSUE TITLE
Plugin Template

### ISSUE THREAD

**Issue by angelleye** [angelleye/divi-paypal#1]
I'd like to build a plugin that adds custom PayPal modules to the Divi theme by Elegant Themes so that people using Divi can easily drop PayPal buttons into their site using a module just like they would other modules in Divi.

This seems to be a good introduction to how to build a custom module for Divi:  http://stackoverflow.com/questions/31565287/how-to-create-custom-divi-module

**Comment by keyurptl** [comment]
To run the module
Please add following line in your child theme **function.php**
`include(get_stylesheet_directory() . '/divi-paypal/custom-pb-paypal-module.php');`
