### ISSUE TITLE
Settings Adjustment

### ISSUE THREAD

**Issue by angelleye** [angelleye/divi-paypal#18]
>Big downside to this.... the account information is in EACH button. I think most would agree that there should be a master setting with an encrypted paypal api code. Then when adding a button it only has to ask you the item details, not the account details each time. Not only does that save time, it would be much safer. Not to mention if you design a site for someone and their PayPal details change you would not have to edit a ton of buttons, just the main setting.

**Comment by keyurptl** [comment]
@angelleye  Created From #20

**Comment by keyurptl** [comment]
@angelleye  
Most of the settings requirements are covered.

**Comment by angelleye** [comment]
@keyurptl After pulling the updated files and creating a new PayPal account in our settings, it's failing because I don't have the new fields in my DB...

>INSERT INTO `aewp_angelleye_paypal_for_divi_companies` (`title`, `account_id`, `paypal_mode`) VALUES ('PHP Sandbox', 'paypalphp@angelleye.com', 'Sandbox')

We need to make sure our update makes the necessary adjustments to the database.

**Comment by keyurptl** [comment]
@angelleye  Try deactivate and activate our plugin.
