### ISSUE TITLE
PayPal WP Button Manager Compatibility

### ISSUE THREAD

**Issue by angelleye** [angelleye/divi-paypal#19]
I'd like to make this Divi module pick up any buttons that have been created by our PayPal WP Button Manager if installed.  

So if you're not using the button manager then you can build the basic buttons directly into Divi like we've done.  If you are using the button manager, then the Divi module would display a drop down or some other method of selecting the PayPal button(s) that you want to add to that particular module.

In a way, this may be available already.  As it stands our Button Manager plugin should be adding a shortcode icon to the WYSIWYG editor that allows you to easily add buttons  you've created.  I've never looked to see if that is available in the Divi Builder editors or not..??

**Comment by keyurptl** [comment]
Created from #18

**Comment by angelleye** [comment]
Let's go ahead and remove the BM drop down altogether if that plugin is not active.  

Then, in #21 we'll be adding information about the BM plugin in the settings panel.

**Comment by angelleye** [comment]
@keyurptl For some reason our drop down is not picking up every button available in the Button Manager system.  For example, you can see here I have quite a few buttons created, and only 2 of them are drafts...

![image](https://cloud.githubusercontent.com/assets/629241/23111394/fd975c14-f6ed-11e6-85ba-0e41862cdba6.png)

When I look in our Divi Module, though, I am only seeing 4 buttons show up in the drop, and then I also get an extra "empty" option in the drop down as well.

![image](https://cloud.githubusercontent.com/assets/629241/23111433/2957280c-f6ee-11e6-9072-6cdd1119b637.png)

**Comment by angelleye** [comment]
@keyurptl I've applied the updates, but I'm still not seeing all of the currently published buttons in the Divi module drop down.  It's still showing me 4 buttons and an empty spot just like above.
