### ISSUE TITLE
Add a PayPal logo as the icon for the module.

### ISSUE THREAD

**Issue by angelleye** [angelleye/divi-paypal#2]
Need to add a PayPal icon/logo on the PayPal Button module selection screen...

![image](https://cloud.githubusercontent.com/assets/629241/22580617/843e48b0-e99f-11e6-95b3-237cc6ba52cf.png)

We can use this icon...

http://fontawesome.io/icon/paypal/

**Comment by keyurptl** [comment]
Added fon-awesome icon http://fontawesome.io/icon/paypal/
