### ISSUE TITLE
Settings Adjustments / Button Front End

### ISSUE THREAD

**Issue by angelleye** [angelleye/divi-paypal#22]
In #18 we added a settings panel which includes the setup of one or more PayPal account IDs.

If you have an existing button on the site already, and then you edit the PayPal account ID of the record related to that button, it's not updating on the front end until after you re-save the PayPal module on the page the button was added to.  This defeats the purpose of having a global PayPal account setting.

We need to find a way to force the module update.  If we can update all related modules when the account record is updated that would be great.  If not, we should look into adding a "Tools" tab to the settings panel, and within that we can create a tool you can use to automatically update all Divi module PayPal buttons if / when necessary.

**Comment by tejasm-itpath** [comment]
As we have discussed on this issue that , We can not do it , because there is no event in wordpress where we can check that page has been changed until it is update,

The same thing is happens in the Advance custom field plugin  , in that also when you changed any custom field you have to resave/update the page to see updates on Page. So the same rule apply here.

@angelleye

**Comment by angelleye** [comment]
@tejasm-itpath What about building a tool that forces it..??  There has to be some way to do that I would think..??

**Comment by tejasm-itpath** [comment]
@angelleye  Yes sure , we will check for it.

**Comment by tejasm-itpath** [comment]
@angelleye
I have tried to find a way to do forcefully update.
Also I can not find any tool or code that checks where our button is placed in the page or which page.
So I think this is not possible to do.

**Comment by angelleye** [comment]
@tejasm-itpath Did you try asking about this on the Divi forum or Facebook communities?

**Comment by tejasm-itpath** [comment]
@angelleye 
No I haven't asked to Divi Forum or Divi Facebook Community.
