### ISSUE TITLE
Notices

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [angelleye/divi-paypal#24]
Hi @tejasm-itpath 

Please take a look at following screenshots, I have installed Divi theme, then Button manager then Paypal for divi, created button, added my paypal details for Paypal for DIVI too. 

Then I went ahead to create a page with the PP button and if the divi builder preview window saw notice as below picture.
![button preview issue](https://cloud.githubusercontent.com/assets/11312949/26767115/2a80b75a-49b6-11e7-83a9-3ea82e41bf60.png)

After save and exit , I saved the page and saw following notices on the desktop.
![on page save got these notices](https://cloud.githubusercontent.com/assets/11312949/26767122/387c7c0e-49b6-11e7-8111-81c69fdba073.png)

Can you give a fix to these, please? Let me know if you need any information on this.

**Comment by tejasm-itpath** [comment]
@MansoorAliKhanOfficial 
Have you created PayPal Button in the PayPal Button Manager Plugin ??
If yes then is it successfully added in your posts data ?

Second thing , we have not added select box/ textbox as you shown in the screenshot ,
We have fields as this https://www.screencast.com/t/NMMOnHrzl

So need more details about how you get "Just another textbox fields/ select box fields" ?

**Comment by tejasm-itpath** [comment]
@MansoorAliKhanOfficial 
I have **define('WP_DEBUG', true);** in config file ,  
I have followed your steps and made video 
Check this link   https://www.screencast.com/t/S9go3VvH
It is working as expected.

**Comment by tejasm-itpath** [comment]
You can check/ search **" paypal_wp_button_manager_email_link "** key  in  **wp_postmeta** " **meta_key" table field**

**Comment by tejasm-itpath** [comment]
Check my above commit @angelleye  @MansoorAliKhanOfficial
