### ISSUE TITLE
Divi 3.1 Dev API

### ISSUE THREAD

**Issue by angelleye** [angelleye/divi-paypal#33]
The new developer API should allow us to more tightly integrate our buttons and make them work with the visual designer

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**This issue now has a bounty of $12.00 attached to it.**

- If you would like to work on this issue you can 'start work' [on the GitCommits Issue Details page](https://sandbox.app.gitcommits.com/issue/git-offers-testing).
- Questions? Checkout [GitCommits Help](https://sandbox.gitcommits.com/faq)
- More funded Bounties are available on the [GitCommits Issue Explorer](https://sandbox.app.gitcommits.com/explorer)

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**This issue now has a bounty of $150.00 attached to it.**

- If you would like to work on this issue you can 'start work' [on the GitCommits Issue Details page](https://sandbox.app.gitcommits.com/issue/divi-31-dev-api).
- Questions? Checkout [GitCommits Help](https://sandbox.gitcommits.com/faq)
- More funded Bounties are available on the [GitCommits Issue Explorer](https://sandbox.app.gitcommits.com/explorer)

**Comment by deepakmaurya** [comment]
### New Message from <a href="http://gitcommits.test/profile/Webnexus">Webnexus</a> to <a href="http://gitcommits.test/profile/deepakmaurya">deepakmaurya</a>:
test 43

**Comment by deepakmaurya** [comment]
** New Message from <a href="http://gitcommits.test/profile/Webnexus">Webnexus</a> to <a href="http://gitcommits.test/profile/deepakmaurya">deepakmaurya</a> **
test 45

**Comment by deepakmaurya** [comment]
**New Message from <a href="http://gitcommits.test/profile/Webnexus">Webnexus</a> to <a href="http://gitcommits.test/profile/deepakmaurya">deepakmaurya</a>**
test 47

**Comment by deepakmaurya** [comment]
**New Message from <a href="http://gitcommits.test/profile/deepakmaurya">deepakmaurya</a> to <a href="http://gitcommits.test/profile/Webnexus">Webnexus</a>**

Testing my message as Github comment

**Comment by deepakmaurya** [comment]
**New Message from <a href="http://gitcommits.test/profile/Webnexus">Webnexus</a> to <a href="http://gitcommits.test/profile/deepakmaurya">deepakmaurya</a>**

This is a test message to post on GitHub.

**Comment by devchristina2** [comment]
Hi,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
