### ISSUE TITLE
Redirect URL option in settings isn't pulling all available pages..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/divi-paypal#34]
* https://wordpress.org/support/topic/redirect-url-not-showing-all-pages

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**This issue has a bounty of $89.00 ready to be claimed!**

- If you are a Contributor and would like to complete this task to claim the bounty you can **Start Work** on the [GitCommits issue details page](https://sandbox.app.gitcommits.com/issue/redirect-url-option-in-settings-isnt-pulling-all-available-pages).
- If you would like to see this issue completed more quickly, please **Add Funding** to the bounty on the [GitCommits issue details page](https://sandbox.app.gitcommits.com/issue/redirect-url-option-in-settings-isnt-pulling-all-available-pages).
- More open bounties are available in the [GitCommits Issue Explorer](https://sandbox.app.gitcommits.com/explorer)
- Questions? Review our [FAQ](https://www.gitcommits.com/faq)

**Comment by devchristina2** [comment]
Hi,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
