### ISSUE TITLE
WordPress Plugin README 

### ISSUE THREAD

**Issue by angelleye** [angelleye/divi-paypal#5]
We need to create our readme.txt file for the WordPress plugin.  Take a look at the readme.txt for PayPal for WooCommerce:  https://github.com/angelleye/paypal-woocommerce/blob/release/readme.txt

That file is what generates this:  https://wordpress.org/plugins/paypal-for-woocommerce/

so the tabs for Description, Installation, FAQ, Screenshots, and Changelog come from the plugin's readme.txt file.

We need to build the readme.txt for this plugin, and we also need to create graphics for the plugin including screenshots.  For example, in the [SVN repo for the WordPress plugin](https://plugins.svn.wordpress.org/paypal-for-woocommerce/), you'll see in the assets folder are the images that get output on that WordPress plugin directory page.  It also includes an icon for the search results when browsing for plugins within the WordPress admin panel.  So you'll notice PayPal for WooCommerce has the following images in the /assets folder:

* banner-1544x500.jpg
* banner-772x250.jpg
* icon-128x128.png
* icon-256x256.png
* screenshot-1.jpg
* screenshot-2.jpg
* screenshot-3.jpg
* screenshot-4.jpg
* screenshot-5.png

So we need to create some screenshots, then save them following the same format as above with the numbers matching the descriptions in our readme.txt file.

The banner images and icon images just need to go in the assets folder for the plugin.  This assets folder is not part of this repo, though, so I just need you to create those graphics and attach them to this issue.

Take a moment to review [each of the plugins we already have posted in the WordPress directory](https://profiles.wordpress.org/angelleye/#content-plugins).  Then build the graphics and the readme.txt for this plugin so that it matches the overall look that we've got with each of our plugins.

**Comment by keyurptl** [comment]
@angelleye  **Please use banner-772x250.png.**

**Comment by angelleye** [comment]
I don't see a banner attached here..??  Also, you need to make sure you do the additional sizes as well.

**Comment by keyurptl** [comment]
Its in the assets folder. and yes also added banner-1544x500.png @angelleye

**Comment by angelleye** [comment]
Ok, so now we removed the /assets folder after explaining that structure, but I still don't see the actual graphics attached for me here so that I can place them in the SVN structure.

**Comment by keyurptl** [comment]
[Added Zip files](https://github.com/angelleye/divi-paypal/commit/082cef26257849ba8a8b9c2fe0ea9768af1d8edb)

**Comment by angelleye** [comment]
I need to make some more adjustments here, but I'm going to finish up the other issues and come back to this.
